name: PR Jira Autolink

on:
  pull_request:
    types: [opened]
  workflow_call:
  merge_group:

permissions:
  pull-requests: write

jobs:
  autolink:
    name: Add Jira Link to PR Title and Description
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}

    steps:
      - uses: tzkhan/pr-update-action@v2
        name: Add Jira Link to PR Title and Description
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '([A-Za-z]{2,4})-(\d{1,5})'
          title-template: "[%headbranch%] "
          title-update-action: "prefix"
          body-template: |
            Jira ticket: [%headbranch%](https://medibank.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: "prefix"

  forceSuccess:
    name: Force Success
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'merge_group' }}
    steps:
      - name: Force Success
        run: exit 0
