name: PR Jira Autolink

on:
  pull_request:
    types: [opened]
  merge_group:

permissions:
  pull-requests: write

jobs:
  autolink:
    name: Add Jira Link to PR Title and Description
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          head-branch-regex: '([A-Za-z]{2,4})-(\d{1,5})'
          title-template: "%headbranch%: "
          title-update-action: prefix
          body-template: |
            Jira ticket: [%headbranch%](https://medibank.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: prefix

  merge-group-success:
    name: Merge Group Success
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - run: true
