name: PR Jira Autolink

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  autolink:
    uses: ahmdigital/.github/.github/workflows/autolink_pr.yml@main
